#!/bin/bash -login
#SBATCH -N 1
#SBATCH -t 1-0:00:00
#SBATCH --ntasks-per-node 2
#SBATCH --mem=40GB

conda activate RM

perl patch_gap.pl NC358_21k_75x_DLE1_consensus_dft.fasta NC358_21k_75x_DLE1_consensus_quick.fasta gap.list
